config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  mount Thredded::Engine => '/forum'

  resources :vagrantfiles do 
    member do 
      get 'download'
    end
  end

  resources :experiments do 
    collection do
      get 'feed', format: 'rss'
    end

    member do 
      get 'followers'
      get 'content'
      get 'serverfile'
      get 'serverfile_content'
      get 'serverfile_download'
    end
  end

=begin
  resources :users, only: [:show] do
    get 'student', to: 'students#show'
    get 'student/new', to: 'students#new'

    post 'student', to: 'students#create'

    put 'student', to: 'students#update'
    patch 'student', to: 'student#update'
  end
=end

  resources :users, only: [:show] do
    resources :submissions
  end

  resources :submissions

  post 'relationships/experiments', to: 'relationships#follow_experiment'
  delete 'relationships/experiments', to: 'relationships#unfollow_experiment'

  # Static controller
  get '/wiki', to: 'static#wiki'
  get '/rss', to: 'static#rss'
  get '/hof', to: 'static#hof'
  get '/feed', to: 'static#feed'

  mount Test::API => '/test' #url: localhost/test/api/v1/hello
  mount Upload::API => '/upload'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_one :judgement, :dependent => :destroy
  has_many :submissions

  has_and_belongs_to_many :users

  validates :title, presence: true

  def generate_vagrantfile_for_followers
    vagrant_nodes = Array.new
    followers = self.users
    followers.each do |follower|
      info = Hash.new
      info['nodename'] = self.title + "_" + follower.stunum[-3..-1]
      info['stunum'] = follower.stunum
      info['stuname'] = follower.stuname
      info['ip'] = "192.168.1#{info['stunum'][-3]}.#{info['stunum'][-2..-1]}"
      vagrant_nodes << info
    end

    vagrantfiles_template = ERB.new %Q[
      Vagrant.configure("2") do |config|
        <% vagrant_nodes.each do |node| %>
          config.vm.define "<%= node['nodename'] %>" do |client|
            client.vm.box = "ubuntu/trusty64"
            client.vm.hostname = "<%= node['stunum'] %>"
            client.vm.network "private_network", ip: "<%= node['ip'] %>"
          end
        <% end %> 
      end
    ].strip
    
    return vagrantfiles_template.result(binding)
  end
end

app/models/judgement.rb
class Judgement < ApplicationRecord
  # 不绑定可以变换对应的experiment
  belongs_to :experiment # 绑定之后不能轻易删除

end

app/models/operatingsystem.rb
class Operatingsystem < ApplicationRecord
  has_many :vagrantfiles, :dependent => :destroy

end

app/models/student.rb
class Student < ApplicationRecord
  
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :experiment
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student

  has_many :submissions
  has_and_belongs_to_many :experiments

  def admin?
    return self.admin
  end

  def student?
    return false if self.stunum == nil
    return true if self.stunum != nil
  end

  def author_name; self.display_name; end
  def name; self.author_name; end

  def display_name
    if self.username.present?
      self.username
    else
      self.email.split("@").first
    end
  end

  def follow_experiment(experiment_id)
    self.experiments << Experiment.find(experiment_id) unless self.experiments.include?(Experiment.find(experiment_id))
  end

  def unfollow_experiment(experiment_id)
    self.experiments.delete(Experiment.find(experiment_id)) if self.experiments.include?(Experiment.find(experiment_id))
  end

  def following?(other_experiment)
    self.experiments.include?(other_experiment)
  end
end

app/models/vagrantfile.rb
class Vagrantfile < ApplicationRecord
  belongs_to :operatingsystem
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @experiments = Experiment.all.page(params[:page]).per(10)
  end

  def show
    @experiment = Experiment.find(params[:id])
    @judgement = @experiment.judgement
    if current_user
      @submissions = current_user.submissions.where(:experiment_id => params[:id]).page(params[:page]).per(10)
    end
  end

  def followers
    @experiment = Experiment.find(params[:id])
    @followers = @experiment.users.page(params[:page]).per(10)
  end

  def content
    @experiment = Experiment.find(params[:id])
  end

  def serverfile
    @experiment = Experiment.find(params[:id])
  end

  def serverfile_content
    @content = Experiment.find(params[:id]).generate_vagrantfile_for_followers
  end

  def serverfile_download
    @experiment = Experiment.find(params[:id])
    # @path = "#{Rails.root}/public/experiments/experiment_#{@experiment.id}_vagrantserverfile.rb"
    # @file = File.open(@path, "w")
    # @file << @experiment.generate_vagrantfile_for_followers
    # @file.close
    # system("ruby-beautify -c 2 -s --overwrite #{@path}")
    
    # send_file(@path, filename: "experiment_#{@experiment.id}_vagrantserverfile.rb", stream: false)
    send_data(@experiment.generate_vagrantfile_for_followers,
              filename: "experiment_#{@experiment.id}_vagrantserverfile.rb")
  end
  
  def new
    @experiment = Experiment.new
    redirect_to root_path, alert: "You have no permission." if !current_user.admin?
  end

  def create
    @experiment = Experiment.new(experiment_params)
    @experiment.author = current_user.author_name
    
    if @experiment.save
      redirect_to experiments_path, notice: "Create experiment success."
    else
      render :new
    end
  end

  def edit
    find_experiment_and_check_permission
  end

  def update 
    find_experiment_and_check_permission
    if @experiment.update(experiment_params)
      redirect_to experiment_path(@experiment), notice: "Update experiment success."
    else
      render :edit
    end
  end

  def destroy 
    find_experiment_and_check_permission

    @experiment.destroy
    redirect_to experiment_path, alert: "Experiment deleted."
  end

  def feed
    @experiments = Experiment.limit(10)
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  private
    def experiment_params
      params.require(:experiment).permit(
        :title, :author, :expiration_date, :content, :remark, :judge)
    end

    def find_experiment_and_check_permission
      @experiment = Experiment.find(params[:id])

      redirect_to root_path, alert: "You have no permission" unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @submissions = @user.submissions.page(params[:page]).per(10)
    @first_experiment = @user.experiments.order(id: :asc).first
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time time
    return time.strftime("%A %d, %b, %Y at %H:%M")
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
  def option_tags
    @systems = Operatingsystem.all; result = []
    @systems.each do |sys|
      result << ["#{sys.system_name} #{sys.system_version}", sys.id]
    end
    result
  end

  def selected_option file
    return file.operatingsystem.id if file.operatingsystem != nil
    return 0
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vagrantfiles_helper.rb
module VagrantfilesHelper
  def format_time time
    return "" if time == nil
    return time.strftime("%A %d, %Y at %H:%M")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/experiments/_follow.html.erb
<div id="follow_form">
<%= form_for current_user, :url => relationships_experiments_path, :html => {:method => :post}, :remote => true do |f| %>
  <div><%= hidden_field_tag :experiment_id, @experiment.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-block" %>
<% end %>
</div>

app/views/experiments/_follower.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Username</th>
      <th>Follower Name</th>
      <th>Follower Number</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @followers.each do |follower| %>
        <tr>
          <td>#</td>
          <td><%= link_to(follower.username, user_path(follower)) %></td>
          <td><%= follower.stuname %></td>
          <td><%= follower.stunum %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<center>
<%= paginate @followers, :theme => 'twitter-bootstrap-3' %>
</center>

app/views/experiments/_form.html.erb
<center><h2>Create new experiment</h2></center>
<br>
<%= form_for @experiment, html: {class: "form-horizontal"} do |f| %>
  <% if @experiment.errors.any? %>
    <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :remark, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :remark, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :expiration_date, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :expiration_date, :class => "form-control", data:{ provide: 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :judge, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :judge, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :content, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  var editor = new Simditor({
          textarea: $('#experiment_content'),
          pasteImage: true,
          defaultImage: '<%= image_path "upload-loading.png" %>',
          upload: {url: '/public/simditor/raraupload'}
      });
  
  var editor = CodeMirror.fromTextArea(document.getElementById("experiment_judge"), {
        lineNumbers: true,     // 显示行数
        indentUnit: 4,         // 缩进单位为4
        //styleActiveLine: true, // 当前行背景高亮
        matchBrackets: true,   // 括号匹配
        mode: 'shell',     // HMTL混合模式
        lineWrapping: true,    // 自动换行
        theme: 'neat',      // 使用dracula模版
        //readOnly: true,
    });

    editor.setOption("extraKeys", {
        // Tab键换成4个空格
        Tab: function(cm) {
            var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
            cm.replaceSelection(spaces);
        },
        // F11键切换全屏
        "F11": function(cm) {
            cm.setOption("fullScreen", !cm.getOption("fullScreen"));
        },
        // Esc键退出全屏
        "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
        }
    });
</script>


app/views/experiments/_generator.html.erb
<form class="form-horizontal">
    <fieldset>
        <div class="form-group">
            <label for="vagrantfile" class="col-lg-2 control-label">VBVMS</label>
            <div class="col-lg-10">
                <div id="editor" >
                    <textarea class="form-control" name = "code" id="code"><%= @experiment.generate_vagrantfile_for_followers %></textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <%= link_to "Download", serverfile_download_experiment_path, class: "btn btn-primary" %>
                <a href="#" class="btn btn-danger">Boot All Virtual Machines On Server</a>
            </div>
        </div>
    <fieldset>
</form>

<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,     // 显示行数
        indentUnit: 4,         // 缩进单位为4
        //styleActiveLine: true, // 当前行背景高亮
        matchBrackets: true,   // 括号匹配
        mode: 'ruby',     // HMTL混合模式
        lineWrapping: true,    // 自动换行
        theme: 'neat',      // 使用dracula模版
        readOnly: true,
    });

    editor.setOption("extraKeys", {
        // Tab键换成4个空格
        Tab: function(cm) {
            var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
            cm.replaceSelection(spaces);
        },
        // F11键切换全屏
        "F11": function(cm) {
            cm.setOption("fullScreen", !cm.getOption("fullScreen"));
        },
        // Esc键退出全屏
        "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
        }
    });

</script>

app/views/experiments/_submission.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Submission ID</th>
      <th>Submission Status</th>
      <th>Submission Create Time</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @submissions.each do |submission| %>
        <tr>
          <td>#</td>
          <td><%= link_to submission.id, submission_path(submission) %></td>
          <td><%= submission.status %></td>
          <td><%= submission.created_at %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<center>
<%= paginate @submissions, :theme => 'twitter-bootstrap-3' %>
</center>

app/views/experiments/_unfollow.html.erb
<div id="follow_form">
<%= form_for current_user, :url => relationships_experiments_path, :html => {:method => :delete}, :remote => true do |f| %>
  <div><%= hidden_field_tag :experiment_id, @experiment.id %></div>
  <%= f.submit "Unfollow", class: "btn btn-primary btn-block" %>
<% end %>
</div>

app/views/experiments/content.html.erb
<div class="well container">
  <center><h2>Experiment Content</h2></center>
  <br />
  <div class="col-md-8 col-md-offset-2">
    <%= @experiment.content.html_safe %>
  </div>
</div>

app/views/experiments/edit.html.erb
<div class="well container">
  <%= render "form" %>
</div>

app/views/experiments/followers.html.erb
<div class="well container">
  <center><h2>Experiment Followers</h2></center>
  <br>
  <%= render "follower" %>
</div>

app/views/experiments/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Experiments</li>
</ul>

<% if current_user && current_user.admin? %>
  <%= link_to "New Experiment", new_experiment_path, class: "btn btn-success" %>
  <hr>
<% end %>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Experiment</th>
      <th>Author</th>
      <th>Release Time</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @experiments.each do |experiment| %>
        <tr>
          <td>#</td>
          <td><%= link_to(experiment.title, experiment_path(experiment)) %></td>
          <td><%= experiment.author %></td>
          <td><%= experiment.created_at %></td>
          <% if current_user && current_user.admin %>
          <td>
            <%= link_to("Modify", edit_experiment_path(experiment), class: "btn btn-xs btn-info") %>
            <%= link_to("Delete", experiment_path(experiment), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
</table>

<center>
<%= paginate @experiments, :theme => 'twitter-bootstrap-3' %>
</center>

app/views/experiments/new.html.erb
<div class="well container">
  <%= render "form" %>
</div>

app/views/experiments/serverfile.html.erb
<div class="well container">
  <center><h2>VBVMS File</h2></center>
  <center><h3>Vagrantfile for Booting Virtual Machine on Server</h3></center>
  <br />
  <%= render "generator" %>
</div>

app/views/experiments/serverfile_content.html.erb
<%= render :plain => @content %>

app/views/experiments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><%= link_to("Home", root_path) %></li>
        <li class="breadcrumb-item active"><%= link_to("Experiments", experiments_path) %></li>
        <li class="breadcrumb-item"><%= @experiment.id %></li>
      </ol>

      <h1>
        <%= @experiment.title %>
      </h1>

      <p class="lead">
        by
        <a href="#"><%= link_to(@experiment.author, "#") %></a>
      </p>

      <% unless !current_user %>
        <div id="follow_form">
          <% if current_user.following?(@experiment) %>
            <%= render 'unfollow' %>
          <% else %>
            <%= render 'follow' %>
          <% end %>
        </div>
      <% end %>

      <hr>
      <h4>
        Posted on <%= format_time @experiment.created_at %>
      </h4>
      <hr>
      
      <% unless !current_user %>
        <h4>Submissions</h4>
        <%= render 'submission'%>
      <% end %>
      
      <hr>
      <!-- <%= render "generator" %>
      <br>
      <a href="#" class="btn btn-primary">Start all virtualmachine</a>
      -->
    </div>

    <div class="col-md-4">
      <div class="list-group">
        <li class="list-group-item text-center">
          Experiment Notice
        </li>
        <a href="#" class="list-group-item list-group-item-action active">
          <h4 class="list-group-item-heading">Expiration Time</h4>
          <p class="list-group-item-text"><%= format_time @experiment.expiration_date %></p>
        </a>
        <%= link_to content_experiment_path(@experiment), class: "list-group-item list-group-item-action" do %>
          <h4 class="list-group-item-heading">Experiment Content</h4>
          <p class="list-group-item-text">Link to the experiment content.</p>
        <% end %>
        <% if current_user && current_user.admin? %>
          <%= link_to followers_experiment_path(@experiment), class: "list-group-item list-group-item-action" do %>
            <h4 class="list-group-item-heading">Experiment Followers</h4>
            <p class="list-group-item-text">Link to the experiment follower.</p>
          <% end %>
        <% end %>

      </div>

      <div class="list-group">
        <li class="list-group-item text-center">
          Files
        </li>
        <a href="#" data-toggle="modal" data-target="#vagrantFile" class="list-group-item list-group-item-action active">
          <h4 class="list-group-item-heading">Requirements</h4>
          <p class="list-group-item-text">Experiment requirements download page.</p>
        </a>

        <%= link_to serverfile_experiment_path(@experiment), class: "list-group-item list-group-item-action" do  %>
          <h4 class="list-group-item-heading">Vagrantfile for server</h4>
          <p class="list-group-item-text">VBVMS file download page.</p>
        <% end %>
      </div>

    </div>

  </div>
</div>

<div class="modal fade" id="vagrantFile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Vagrantfile for server</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary">提交更改</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal -->
</div>