config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  mount Thredded::Engine => '/forum'

  resources :vagrantfiles do 
    member do 
      get 'download'
    end
  end

  resources :experiments do 
    collection do
      get 'feed', format: 'rss'
    end

    member do 
      get 'followers'
      get 'content'
      get 'serverfile'
      get 'serverfile_content'
      get 'serverfile_download'
    end
  end

=begin
  resources :users, only: [:show] do
    get 'student', to: 'students#show'
    get 'student/new', to: 'students#new'

    post 'student', to: 'students#create'

    put 'student', to: 'students#update'
    patch 'student', to: 'student#update'
  end
=end

  resources :users, only: [:show] do
    resources :submissions
  end

  resources :submissions

  post 'relationships/experiments', to: 'relationships#follow_experiment'
  delete 'relationships/experiments', to: 'relationships#unfollow_experiment'

  # Static controller
  get '/wiki', to: 'static#wiki'
  get '/rss', to: 'static#rss'
  get '/hof', to: 'static#hof'
  get '/feed', to: 'static#feed'

  mount Test::API => '/test' #url: localhost/test/api/v1/hello
  mount Upload::API => '/upload'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_one :judgement, :dependent => :destroy
  has_many :submissions

  has_and_belongs_to_many :users

  validates :title, presence: true

  def generate_vagrantfile_for_followers
    vagrant_nodes = Array.new
    followers = self.users
    followers.each do |follower|
      info = Hash.new
      info['nodename'] = self.title + "_" + follower.stunum[-3..-1]
      info['stunum'] = follower.stunum
      info['stuname'] = follower.stuname
      info['ip'] = "192.168.1#{info['stunum'][-3]}.#{info['stunum'][-2..-1]}"
      vagrant_nodes << info
    end

    vagrantfiles_template = ERB.new %Q[
      Vagrant.configure("2") do |config|
        <% vagrant_nodes.each do |node| %>
          config.vm.define "<%= node['nodename'] %>" do |client|
            client.vm.box = "ubuntu/trusty64"
            client.vm.hostname = "<%= node['stunum'] %>"
            client.vm.network "private_network", ip: "<%= node['ip'] %>"
          end
        <% end %> 
      end
    ].strip
    
    return vagrantfiles_template.result(binding)
  end
end

app/models/judgement.rb
class Judgement < ApplicationRecord
  # 不绑定可以变换对应的experiment
  belongs_to :experiment # 绑定之后不能轻易删除

end

app/models/operatingsystem.rb
class Operatingsystem < ApplicationRecord
  has_many :vagrantfiles, :dependent => :destroy

end

app/models/student.rb
class Student < ApplicationRecord
  
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :experiment
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student

  has_many :submissions
  has_and_belongs_to_many :experiments

  def admin?
    return self.admin
  end

  def student?
    return false if self.stunum == nil
    return true if self.stunum != nil
  end

  def author_name; self.display_name; end
  def name; self.author_name; end

  def display_name
    if self.username.present?
      self.username
    else
      self.email.split("@").first
    end
  end

  def follow_experiment(experiment_id)
    self.experiments << Experiment.find(experiment_id) unless self.experiments.include?(Experiment.find(experiment_id))
  end

  def unfollow_experiment(experiment_id)
    self.experiments.delete(Experiment.find(experiment_id)) if self.experiments.include?(Experiment.find(experiment_id))
  end

  def following?(other_experiment)
    self.experiments.include?(other_experiment)
  end
end

app/models/vagrantfile.rb
class Vagrantfile < ApplicationRecord
  belongs_to :operatingsystem
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @submissions = @user.submissions.page(params[:page]).per(10)
    @first_experiment = @user.experiments.order(id: :asc).first
  end
end

app/controllers/vagrantfiles_controller.rb
class VagrantfilesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @vagrantfiles = Vagrantfile.all.page(params[:page]).per(10)
  end

  def show
    @vagrantfile = Vagrantfile.find(params[:id])
  end

  def new
    @vagrantfile = Vagrantfile.new
    redirect_to root_path, alert: "You have no permission." if !current_user.admin?
  end

  def edit
    find_vagrantfile_and_check_permission
  end

  def create
    @vagrantfile = Vagrantfile.new(vagrantfile_params)
    @vagrantfile.author = current_user.author_name
    @vagrantfile.operatingsystem = Operatingsystem.find(vagrantfile_params[:operatingsystem_id])

    if @vagrantfile.save
      redirect_to vagrantfiles_path, notice: "Create vagrantfile success."
    else
      render :new
    end
  end

  def update
    find_vagrantfile_and_check_permission
    if @vagrantfile.update(vagrantfile_params)
      redirect_to vagrantfile_path(@vagrantfile), notice: "Update vagrantfile success."
    else
      render :edit
    end
  end

  def destroy
    find_vagrantfile_and_check_permission

    @vagrantfile.destroy
    redirect_to vagrantfiles_path, alert: "Vagrantfile deleted"
  end

  def download
    @vagrantfile = Vagrantfile.find(params[:id])
    send_data(@vagrantfile.configure,
              filename: "Vagrantfile")
  end

  private
    def vagrantfile_params
      params.require(:vagrantfile).permit(
        :filename, :remark, :configure, :system_name, :system_version, :version, :operatingsystem_id)
    end

    def find_vagrantfile_and_check_permission
      @vagrantfile = Vagrantfile.find(params[:id])

      redirect_to root_path, alert: "You have no permission" unless current_user.admin?
    end

end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time time
    return time.strftime("%A %d, %b, %Y at %H:%M")
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
  def option_tags
    @systems = Operatingsystem.all; result = []
    @systems.each do |sys|
      result << ["#{sys.system_name} #{sys.system_version}", sys.id]
    end
    result
  end

  def selected_option file
    return file.operatingsystem.id if file.operatingsystem != nil
    return 0
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vagrantfiles_helper.rb
module VagrantfilesHelper
  def format_time time
    return "" if time == nil
    return time.strftime("%A %d, %Y at %H:%M")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/vagrantfiles/_form.html.erb
<%= form_for @vagrantfile, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :filename, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :filename, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :System, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.select :operatingsystem_id, options_for_select(option_tags, selected_option(@vagrantfile)), {}, {:class => "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :version, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :version, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :remark, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :remark, :class => "form-control", :rows => "3" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :configure, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :configure, :class => "form-control", :rows => "10" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

<script>
var editor = CodeMirror.fromTextArea(document.getElementById("vagrantfile_configure"), {
        lineNumbers: true,     // 显示行数
        indentUnit: 4,         // 缩进单位为4
        //styleActiveLine: true, // 当前行背景高亮
        matchBrackets: true,   // 括号匹配
        mode: 'ruby',     // HMTL混合模式
        lineWrapping: true,    // 自动换行
        theme: 'neat',      // 使用dracula模版
        //readOnly: true,
    });

    editor.setOption("extraKeys", {
        // Tab键换成4个空格
        Tab: function(cm) {
            var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
            cm.replaceSelection(spaces);
        },
        // F11键切换全屏
        "F11": function(cm) {
            cm.setOption("fullScreen", !cm.getOption("fullScreen"));
        },
        // Esc键退出全屏
        "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
        }
    });

</script>

app/views/vagrantfiles/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Vagrantfiles</li>
</ul>

<% if current_user && current_user.admin? %>
  <%= link_to "New Vagrantfile", new_vagrantfile_path, class: "btn btn-success" %>
  <hr>
<% end %>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Vagrantfile</th>
      <th>Author</th>
      <th>Release Time</th>
    </tr>
  </thead>
  <tbody>
    <tbody>
      <% @vagrantfiles.each do |vagrantfile| %>
        <tr>
          <td>#</td>
          <td><%= link_to(vagrantfile.filename, vagrantfile_path(vagrantfile)) %></td>
          <td><%= vagrantfile.author %></td>
          <td><%= vagrantfile.created_at %></td>
          <% if current_user && current_user.admin %>
          <td>
            <%= link_to("Modify", edit_vagrantfile_path(vagrantfile), class: "btn btn-xs btn-info") %>
            <%= link_to("Delete", vagrantfile_path(vagrantfile), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
</table>
<center>
<%= paginate @vagrantfiles, :theme => 'twitter-bootstrap-3' %>
</center>

app/views/vagrantfiles/new.html.erb
<div class="well container">
  <%= render "form" %>

</div>

app/views/vagrantfiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><%= link_to("Home", root_path) %></li>
        <li class="breadcrumb-item active"><%= link_to("Vagrantfiles", vagrantfiles_path) %></li>
        <li class="breadcrumb-item"><%= @vagrantfile.id %></li>
      </ol>

      <h1>
        <%= @vagrantfile.filename %>
        <small><%= @vagrantfile.operatingsystem.system_name + " " + @vagrantfile.operatingsystem.system_version %></small>
      </h1>

      <p class="lead">
        by
        <a href="#"><%= link_to(@vagrantfile.author, "#") %></a>
      </p>

      <hr>
      <h4>Posted on <%= format_time @vagrantfile.created_at %></h4>
      <hr>

      <div id="editor" >
        <textarea class="form-control" name = "code" id="code"><%= @vagrantfile.configure %></textarea>
        <br />
        <%= link_to("Edit", edit_vagrantfile_path, class: "btn btn-primary btn-lg") %>
        <%= link_to("Download", download_vagrantfile_path, class: "btn btn-default btn-lg") %>
      </div>

    </div>

    <div class="col-md-4">
      <div class="list-group">
        <li class="list-group-item text-center">
          File Information
        </li>
        <a href="#" class="list-group-item list-group-item-action active">
          <h4 class="list-group-item-heading">File Version</h4>
          <p class="list-group-item-text">Version <%= @vagrantfile.version %></p>
        </a>
        <a href="#" class="list-group-item list-group-item-action">
          <h4 class="list-group-item-heading">File Remark</h4>
          <p class="list-group-item-text"><%= @vagrantfile.remark %></p>
        </a>
      </div>

    </div>

  </div>
</div>

<script>
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,     // 显示行数
        indentUnit: 4,         // 缩进单位为4
        //styleActiveLine: true, // 当前行背景高亮
        matchBrackets: true,   // 括号匹配
        mode: 'ruby',     // HMTL混合模式
        lineWrapping: true,    // 自动换行
        theme: 'neat',      // 使用dracula模版
        readOnly: true,
    });

    editor.setOption("extraKeys", {
        // Tab键换成4个空格
        Tab: function(cm) {
            var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
            cm.replaceSelection(spaces);
        },
        // F11键切换全屏
        "F11": function(cm) {
            cm.setOption("fullScreen", !cm.getOption("fullScreen"));
        },
        // Esc键退出全屏
        "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
        }
    });

</script>