config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  mount Thredded::Engine => '/forum'

  resources :vagrantfiles do 
    member do 
      get 'download'
    end
  end

  resources :experiments do 
    collection do
      get 'feed', format: 'rss'
    end

    member do 
      get 'followers'
      get 'content'
      get 'serverfile'
      get 'serverfile_content'
      get 'serverfile_download'
    end
  end

=begin
  resources :users, only: [:show] do
    get 'student', to: 'students#show'
    get 'student/new', to: 'students#new'

    post 'student', to: 'students#create'

    put 'student', to: 'students#update'
    patch 'student', to: 'student#update'
  end
=end

  resources :users, only: [:show] do
    resources :submissions
  end

  resources :submissions

  post 'relationships/experiments', to: 'relationships#follow_experiment'
  delete 'relationships/experiments', to: 'relationships#unfollow_experiment'

  # Static controller
  get '/wiki', to: 'static#wiki'
  get '/rss', to: 'static#rss'
  get '/hof', to: 'static#hof'
  get '/feed', to: 'static#feed'

  mount Test::API => '/test' #url: localhost/test/api/v1/hello
  mount Upload::API => '/upload'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_one :judgement, :dependent => :destroy
  has_many :submissions

  has_and_belongs_to_many :users

  validates :title, presence: true

  def generate_vagrantfile_for_followers
    vagrant_nodes = Array.new
    followers = self.users
    followers.each do |follower|
      info = Hash.new
      info['nodename'] = self.title + "_" + follower.stunum[-3..-1]
      info['stunum'] = follower.stunum
      info['stuname'] = follower.stuname
      info['ip'] = "192.168.1#{info['stunum'][-3]}.#{info['stunum'][-2..-1]}"
      vagrant_nodes << info
    end

    vagrantfiles_template = ERB.new %Q[
      Vagrant.configure("2") do |config|
        <% vagrant_nodes.each do |node| %>
          config.vm.define "<%= node['nodename'] %>" do |client|
            client.vm.box = "ubuntu/trusty64"
            client.vm.hostname = "<%= node['stunum'] %>"
            client.vm.network "private_network", ip: "<%= node['ip'] %>"
          end
        <% end %> 
      end
    ].strip
    
    return vagrantfiles_template.result(binding)
  end
end

app/models/judgement.rb
class Judgement < ApplicationRecord
  # 不绑定可以变换对应的experiment
  belongs_to :experiment # 绑定之后不能轻易删除

end

app/models/operatingsystem.rb
class Operatingsystem < ApplicationRecord
  has_many :vagrantfiles, :dependent => :destroy

end

app/models/student.rb
class Student < ApplicationRecord
  
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :experiment
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student

  has_many :submissions
  has_and_belongs_to_many :experiments

  def admin?
    return self.admin
  end

  def student?
    return false if self.stunum == nil
    return true if self.stunum != nil
  end

  def author_name; self.display_name; end
  def name; self.author_name; end

  def display_name
    if self.username.present?
      self.username
    else
      self.email.split("@").first
    end
  end

  def follow_experiment(experiment_id)
    self.experiments << Experiment.find(experiment_id) unless self.experiments.include?(Experiment.find(experiment_id))
  end

  def unfollow_experiment(experiment_id)
    self.experiments.delete(Experiment.find(experiment_id)) if self.experiments.include?(Experiment.find(experiment_id))
  end

  def following?(other_experiment)
    self.experiments.include?(other_experiment)
  end
end

app/models/vagrantfile.rb
class Vagrantfile < ApplicationRecord
  belongs_to :operatingsystem
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @submissions = @user.submissions.page(params[:page]).per(10)
    @first_experiment = @user.experiments.order(id: :asc).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time time
    return time.strftime("%A %d, %b, %Y at %H:%M")
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
  def option_tags
    @systems = Operatingsystem.all; result = []
    @systems.each do |sys|
      result << ["#{sys.system_name} #{sys.system_version}", sys.id]
    end
    result
  end

  def selected_option file
    return file.operatingsystem.id if file.operatingsystem != nil
    return 0
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vagrantfiles_helper.rb
module VagrantfilesHelper
  def format_time time
    return "" if time == nil
    return time.strftime("%A %d, %Y at %H:%M")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>
	

app/views/common/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; VManagement 2018</p>
  </div>
</footer>

app/views/common/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">VManagement</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li><%= link_to("Vagrantfiles", vagrantfiles_path) %></li>
        <li><%= link_to("Forum", thredded_path) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Experiments <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to("Experiments", experiments_path) %></li>
            <li><%= link_to("New Experiment", new_experiment_path) %></li>
            <li class="divider"></li>
            <li><%= link_to("Submissions", submissions_path) %></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li><%= link_to("Announcements", "#") %><li>
        <li><%= link_to("Wiki", wiki_path) %></li>
        <li><%= link_to("HOF", hof_path) %></li>
        <li><%= link_to("RSS", rss_path)%></li>
        <li><a href="http://labs.syhdaily.com">DIND</a></li>
      </ul>

      <% if !current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Sign Up", new_user_registration_path) %></li>
          <li><%= link_to("Sign In", new_user_session_path) %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wheelchair" aria-hidden="true"></i> <%= current_user.display_name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="download">
              <li><%= link_to("Show", user_path(current_user)) %></li>
              <li><%= link_to("Submissions", user_submissions_url(current_user)) %></li>
              <li><%= link_to("Update", edit_user_registration_path) %></li>
              <li><%= link_to("Log out", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagrantfileManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
    </div>

    <div class="container">
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <br /><br />
    <%= render "common/footer" %>
  </body>
</html>

app/views/thredded/posts/_post.html.erb
<% post, content = post_and_content if local_assigns.key?(:post_and_content) %>
<%= content_tag :article, id: dom_id(post), class: "thredded--post thredded--#{post.read_state}--post" do %>
  <%= render 'thredded/posts_common/actions', post: post, actions: local_assigns[:actions] %>
  <%= render 'thredded/posts_common/header', post: post %>
  <%= content || render('thredded/posts/content', post: post) %>
  <% if post.pending_moderation? && !Thredded.content_visible_while_pending_moderation %>
    <p class="thredded--alert thredded--alert-warning"><%= t 'thredded.posts.pending_moderation_notice' %></p>
  <% elsif post.blocked? && post.can_moderate? %>
    <p class="thredded--alert thredded--alert-danger">
      <%= render 'thredded/shared/content_moderation_blocked_state', moderation_record: post.last_moderation_record %>
    </p>
  <% end %>
<% end %>